
---
name: Pull Request
description: Thank you for contributing to pyRevit! 🎉
title: "fix: "

body:
  - type: checkboxes
    id: checklist
    attributes:
      label: ✈ Checklist
      description: Before submitting your pull request, ensure the following requirements are met:
      options:
        - label: Code follows the [PEP 8](https://peps.python.org/pep-0008/) style guide.
        - label: Changes are tested and verified to work as expected.
        - label: Code has been formatted with [Black](https://github.com/psf/black) using the command: `pipenv run black {source_file_or_directory}`
  - type: textarea
    id: description
    attributes:
      label: 💻Describe the PR
      description: Please provide a brief description of the changes introduced in this pull request. Explain the purpose of these changes and their intended effect on the project.
    validations:
      required: true
  - type: textarea
    id: related_issues
    attributes:
      label: Related Issues
      value: |
      If applicable, link the issues resolved by this pull request
      - Resolves #[issue number]
    validations:
      required: true
  - type: textarea
    id: additional_notes
    attributes:
      label: Additional Notes
      value: |
      ## Additional Notes
      Include any additional context, screenshots, or considerations for reviewers.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |  
      ---
     🎉Thanks for taking the time to fill out this bug report. 🙌
