name: Build test
on:
  push:
  workflow_dispatch:

env:
  netfx_path: dev\libs\netfx
  netcore_path: dev\libs\netcore

  nlog_path: dev\modules\pyRevitLabs.NLog\src\Nlog\
  mahapps.metro_path: dev\modules\pyRevitLabs.MahApps.Metro\src\MahApps.Metro\
  newtonsoft.json_path: dev\modules\pyRevitLabs.Newtonsoft.Json\src\Newtonsoft.Json\

  ironpython2_path: dev\modules\pyRevitLabs.ironpython2\src\IronPython\
  ironpython2.modules_path: dev\modules\pyRevitLabs.ironpython2\src\IronPython.Modules\
  ironpython2.sqlite_path: dev\modules\pyRevitLabs.ironpython2\src\IronPython.SQLite\
  ironpython2.wpf_path: dev\modules\pyRevitLabs.ironpython2\src\IronPython.Wpf\

  ironpython3_path: dev\modules\pyRevitLabs.ironpython3\src\IronPython\
  ironpython3.modules_path: dev\modules\pyRevitLabs.ironpython3\src\IronPython.Modules\
  ironpython3.sqlite_path: dev\modules\pyRevitLabs.ironpython3\src\IronPython.SQLite\
  ironpython3.wpf_path: dev\modules\pyRevitLabs.ironpython3\src\IronPython.Wpf\

jobs:
  build:
    if: github.repository != 'eirannejad/pyRevit'
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Prepare .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Prepare msbuild
        uses: microsoft/setup-msbuild@v2

      - name: Build NLog
        run: |
          dotnet build -c Release -f netstandard2.0 -o ${{ env.netfx_path }} ${{ env.nlog_path }}
          dotnet build -c Release -f netstandard2.0 -o ${{ env.netcore_path }} ${{ env.nlog_path }}

      - name: Build MahApps.Metro
        run: |
          dotnet build -c Release -f net47 -o ${{ env.netfx_path }} ${{ env.mahapps.metro_path }}
          dotnet build -c Release -f netcoreapp3.1 -o ${{ env.netcore_path }} ${{ env.mahapps.metro_path }}

      - name: Build Newtonsoft.Json
        run: |
          dotnet build -c Release -f net45 -o ${{ env.netfx_path }} ${{ env.newtonsoft.json_path }}
          dotnet build -c Release -f net6.0 -o ${{ env.netcore_path }} ${{ env.newtonsoft.json_path }}

      - name: Build IronPython2
        run: |
          dotnet build -c Release -f net462 -o ${{ env.netfx_path }} ${{ env.ironpython2_path }}
          dotnet build -c Release -f net462 -o ${{ env.netfx_path }} ${{ env.ironpython2.modules_path }}
          dotnet build -c Release -f net462 -o ${{ env.netfx_path }} ${{ env.ironpython2.sqlite_path }}
          dotnet build -c Release -f net462 -o ${{ env.netfx_path }} ${{ env.ironpython2.wpf_path }}
          
          dotnet build -c Release -f netstandard2.0 -o ${{ env.netcore_path }} ${{ env.ironpython2_path }}
          dotnet build -c Release -f netstandard2.0 -o ${{ env.netcore_path }} ${{ env.ironpython2.modules_path }}
          dotnet build -c Release -f netstandard2.0 -o ${{ env.netcore_path }} ${{ env.ironpython2.sqlite_path }}
          dotnet build -c Release -f net6.0-windows -o ${{ env.netcore_path }} ${{ env.ironpython2.wpf_path }}

      - name: Build IronPython3
        run: |
          dotnet build -c Release -f net462 -o ${{ env.netfx_path }} ${{ env.ironpython3_path }}
          dotnet build -c Release -f net462 -o ${{ env.netfx_path }} ${{ env.ironpython3.modules_path }}
          dotnet build -c Release -f net462 -o ${{ env.netfx_path }} ${{ env.ironpython3.sqlite_path }}
          dotnet build -c Release -f net462 -o ${{ env.netfx_path }} ${{ env.ironpython3.wpf_path }}
          
          dotnet build -c Release -f net6.0 -o ${{ env.netcore_path }} ${{ env.ironpython3_path }}
          dotnet build -c Release -f net6.0 -o ${{ env.netcore_path }} ${{ env.ironpython3.modules_path }}
          dotnet build -c Release -f net6.0 -o ${{ env.netcore_path }} ${{ env.ironpython3.sqlite_path }}
          dotnet build -c Release -f net6.0-windows -o ${{ env.netcore_path }} ${{ env.ironpython3.wpf_path }}